- name: Deploy Scientific Calculator
  hosts: remote_server
  become: yes
  tasks:
    - name: Pull the latest Docker image
      command: docker pull manasmann/scientific-calculator:v1

    - name: Remove any existing container (if running)
      command: docker rm -f scientific-calculator-container
      ignore_errors: yes  # Ignore errors if the container does not exist

    - name: Run the Docker container
      command: docker run -d --name scientific-calculator-container -i -t manasmann/scientific-calculator:v1
